eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA SERVER ADDRESS:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
